[programs.localnet]
mint_pool = "CpYpw2Z6buf1vAGAmZPNz57pJadnrACJ1B3GJHNCSae8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./treasury.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"